name: shopify_merchant_app
description: "A premium Shopify Merchant application."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  go_router: ^14.1.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  pinput: ^4.0.0 # Often useful for OTP/Auth
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
